### ISSUE TITLE
Duplicate SID names at EGCN

### ISSUE THREAD

**Issue by Crabcontrollerdave** [IVAO-XU/EG-Sector-File#37]
![Screenshot_78](https://user-images.githubusercontent.com/97228342/148643064-e62ab7a5-6524-471d-bfd2-04446ab283c4.png)

Duplicated names for ROXOG and UPTON SID's at EGCN Doncaster. I checked the procedure fix's there Ok, I think the issue lies with the names of the sids in the egcn.sid file. Its the same with both 02/20 Departures.

**Comment by RadarController** [comment]
Hi @Crabcontrollerdave, the reason it looks like that is because Doncaster has departures that reach at ROGAG or UPTON, but then continue on to connect to the airway structure! (DESIG, HON, MONTY, etc.)

We can sort this once the new feature exists in Aurora (which should be soon!) This is the format the developer has sent:

> Added to sid/star files transition field as 6th field. 
> eg
> `EHAM;24;KUDA3S;KUDAD;KUDAD;0;LEKKO WOODY;`
> so if 1st point in FP is WOODY it will show also the "KUDA3S 24" in the waypointlist. this 6th field can have multiple points in separated by SPACE.

I'll advise once this is sorted, but for now I won't accept the pull request if that's ok.

Thanks!

**Comment by RadarController** [comment]
Also for my reference it's actually the SEVENTH field, the sixth is the 0 that defines it's a SID. Will need to add that zero to them all too.

**Comment by Crabcontrollerdave** [comment]
Ahh that makes sense now Chris! Yeah that's no worries disregard the pull request

**Comment by RadarController** [comment]
Leaving this open to remind myself to fix it :)

**Comment by RadarController** [comment]
This isn't as easy as I first thought. Because the SIDs have different airway joining routes it's quite difficult to make it work. I might just allocate the ROGAG SIDs to the airway joining points and not draw the exact route after ROGAG>
